/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jmacro;

import java.io.FileNotFoundException;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bcochrane
 */
public class EditDialog extends javax.swing.JFrame {

    /**
     * Creates new form EditDialog
     */
    public EditDialog() {
        pathname = "";
        initComponents();
    }
    
    public EditDialog(String path) {
        pathname = path;
        initComponents();
        initTextArea();
    }
    
    private void initTextArea() {
        if (!pathname.equals("")) {
            try {
                MFLfile = new java.io.File(pathname);
                String s = "";
                java.util.Scanner sc = new java.util.Scanner(MFLfile);
                while (sc.hasNext()) {
                    s += sc.nextLine() + "\n";
                }
                editTextArea.setText(s);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(EditDialog.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("Pathname is empty!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        editTextArea = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editTextArea.setColumns(20);
        editTextArea.setRows(5);
        editTextArea.setText("Something has gone terribly wrong!\nYour file could not be loaded.\nSorry.");
        jScrollPane1.setViewportView(editTextArea);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(pathname))) {
                writer.write(editTextArea.getText() + "\n");
                System.out.println(editTextArea.getText());
            }
        } catch (Exception e) {
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    
    private java.io.File MFLfile;
    private String pathname;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea editTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
